name: CI Pipeline
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build Application
        run: npm run build