name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Enable manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx with Cloud Builder
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "mawazawa/piya"
          install: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.DOCKER_USER }}/deep-wordsmith:latest
          # For pull requests, export to build cache only
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
          cache-from: type=registry,ref=${{ vars.DOCKER_USER }}/deep-wordsmith:buildcache
          cache-to: ${{ github.event_name != 'pull_request' && 'type=registry,ref=${{ vars.DOCKER_USER }}/deep-wordsmith:buildcache,mode=max' || '' }}